import { Inter } from "next/font/google";
import "../styles/globals.css";
import { TheFooter, TheHeader } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "USA Website Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <TheHeader />
        <main className="container">{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
